version: '3.8'  # Using Docker Compose file format version 3.8

services:
  postgres:
    image: postgres:latest  # Use the latest official PostgreSQL image
    environment:
      POSTGRES_PASSWORD: postgres123  # Sets the superuser password
      POSTGRES_USER: postgres         # Sets the superuser name
      POSTGRES_DB: auctionsdb         # Sets the default database to be created
    ports:
      - "5432:5432"  # Maps port 5432 of the container to port 5432 on the host
    volumes:
      - ./mylocal_pgdata:/var/lib/postgresql/data  # Bind mount for PostgreSQL data

# Note: No 'volumes' section needed for bind mounts as we define the path directly
