version: '3.8'

networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_DB=auctionsdb
    ports:
      - "5432:5432"
    volumes:
      - ./mylocal_pgdata:/var/lib/postgresql/data
    networks:
      custom:
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo123
    ports:
      - "27017:27017"
    volumes:
      - ./mylocal_mongodata:/var/lib/mongodb/data
    networks:
      custom:
    healthcheck:
      test: ["CMD-SHELL", "echo 'db.runCommand(\"ping\").ok' | mongosh localhost:27017/test --quiet"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      custom:
    healthcheck:
      test: ["CMD-SHELL", "rabbitmqctl status"]
      interval: 10s
      timeout: 5s
      retries: 5

  auction-svc:
    image: ashutoshpandey/casties-auction-svc:latest
    build:
      context: .
      dockerfile: src/AuctionService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_URLS=http://+:7777
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres123;Database=auctionsdb;
      - IdentityServiceUrl=http://identity-svc
      - Kestrel__Endpoints__Grpc__Protocols=Http2
      - Kestrel__Endpoints__Grpc__Url=http://+:7777
      - Kestrel__Endpoints__WebApi__Protocols=Http1
      - Kestrel__Endpoints__WebApi__Url=http://+:80
    ports:
      - "7001:80"
      - "7777:7777"
    networks:
      custom:
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  search-svc:
    image: ashutoshpandey/casties-search-svc:latest
    build:
      context: .
      dockerfile: src/SearchService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=mongodb://root:mongo123@mongo:27017/auctionsdb?authSource=admin
      - AuctionServiceUrl=http://auction-svc
    ports:
      - "7002:80"
    networks:
      custom:
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  bid-svc:
    image: ashutoshpandey/casties-bid-svc:latest
    build:
      context: .
      dockerfile: src/BiddingService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
      - ConnectionStrings__DefaultConnection=mongodb://root:mongo123@mongo:27017/auctionsdb?authSource=admin
      - IdentityServiceUrl=http://identity-svc
      - GrpcAuction=http://auction-svc:7777
    ports:
      - "7003:80"
    networks:
      custom:
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  identity-svc:
    image: ashutoshpandey/casties-identity-svc:latest
    build:
      context: .
      dockerfile: src/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      #- ClientApp=http://localhost:3000
      - ClientApp=https://app.auction.com    # added in host file
      - ClientSecret=NotASecret
      - ConnectionStrings__DefaultConnection=Server=postgres:5432;User Id=postgres;Password=postgres123;Database=auctionsdb;
      - VIRTUAL_HOST=id.auction.com
    # commented ports because we are using nginx proxy - VIRTUAL_HOST 
    # ports:
    #   - "80:80"
    networks:
      custom:
        ipv4_address: 10.5.0.200
    depends_on:
      postgres:
        condition: service_healthy

  gateway-svc:
    image: ashutoshpandey/casties-gateway-svc:latest
    build:
      context: .
      dockerfile: src/GatewayService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
      - ASPNETCORE_URLS=http://+:80
      - VIRTUAL_HOST=api.auction.com
      - ClientApp=https://app.auction.com
    # commented ports because we are using nginx proxy - VIRTUAL_HOST
    # ports:
    #   - "6001:80"
    networks:
      custom:
    depends_on:
      rabbitmq:
        condition: service_healthy

  notification-svc:
    image: ashutoshpandey/casties-notification-svc:latest
    build:
      context: .
      dockerfile: src/NotificationService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - RabbitMq__Host=rabbitmq
    ports:
      - "7004:80"
    networks:
      custom:
    depends_on:
      rabbitmq:
        condition: service_healthy

  web-app:
    image: ashutoshpandey/casties-web-app
    build:
      context: .
      dockerfile: frontend/web-app/Dockerfile
    volumes:
      - /var/lib/web/data
    # commented ports because we are using nginx proxy - VIRTUAL_HOST
    # ports:
    #   - "3000:3000"
    extra_hosts:
      - id.auction.com:10.5.0.200
    environment:
      - NEXTAUTH_SECRET=somethingreallyreallysecret
      - CLIENT_SECRET=NotASecret
      #- NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_URL=https://app.auction.com
      - NEXTAUTH_URL_INTERNAL=http://web-app:3000
      - API_URL=http://gateway-svc/
      - ID_URL=http://id.auction.com   # add this entry in OS host file
      - NEXT_PUBLIC_NOTIFY_URL=http://gateway-svc/notifications
      - VIRTUAL_HOST=app.auction.com
      - VIRTUAL_PORT=3000
    networks:
      custom:
    depends_on:
      - identity-svc
      - gateway-svc

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./devcerts:/etc/nginx/certs
    networks:
      custom:
    environment:
      - HTTPS_METHOD=noredirect
